Resolve potential client side UV bypass in passkeys
kanidm/webauthn-rs pull request #284
Opened 2023-02-21 07:37 UTC by Firstyear

Fixes #281 In response to this issue we should take proactive steps to prevent client side UV bypassing in our apis. Since firefox is soon to gain CTAP2 support, being the last limiting factor for this, I believe it's time to enforce required UV in passkey flows. Since this won't be released for a bit until some other library changes occur, we can wait for ff to support this by default. 

- [ x ] cargo test has been run and passes
- [ ] documentation has been updated with relevant examples (if relevant)

2023-02-21 11:12 UTC, yaleman approved these changes

2023-02-22 02:53 UTC, Firstyear commented
Okay, I had a chat to @micolous and we decided that since this actually might break already registered credentials such as u2f, then we have to wait to see what apple does about their UV bypass issues in passkeys. If they fix it, then we can leave this as is. If they don't fix it, then we'll need to enforce this to work around the security hole.

2023-02-22 02:59 UTC, micolous requested changes
Per discussion, lets wait for Apple on this one, as this will be a breaking change for some users, especially for U2F-only keys.

This will need documentation, ideally *before* this gets pushed out so that library users have a chance to plan for it.

This should have an escape hatch of some kind as well (feature flag?), particularly as even if Firefox stable gets FIDO2 support on non-Windows platforms, there's still the LTS branch which is carried by a bunch of Linux distributions.

2023-03-14 22:33 UTC, Firstyear commented
In a mail to the webauthn mailing list, the chrome team have now confirmed they have altered their uv preferred behaviour to match safaris allowing the "peripheral exchange bypass".

This means that for libraries outside of webauthn-rs, uv=preferred is once again bypassable, but for us it means there are potential inconsistencies in user experience and behaviour.

I think we need to make uv=required the default as a result of this since we now have two browsers that are susceptible to peripheral change affecting uv status.

2023-03-16 23:21 UTC, Firstyear commented
Mail description btw

> Starting with [Chrome 113](https://chromiumdash.appspot.com/schedule), Chrome’s macOS platform authenticator will no longer prompt for either factor if the Relying Party sets the [User Verification Requirement](https://www.w3.org/TR/webauthn-2/#enum-userVerificationRequirement) for the request to “preferred” or “discouraged” and Touch ID is unavailable. If the User Verification Requirement is set to “required”, Chrome continues to enforce user verification as before, and falls back to prompting for the device password if necessary. The [UV bit](https://www.w3.org/TR/webauthn-2/#flags) in the response will faithfully reflect whether user verification was performed or not.
> 
> This change minimizes user disruption flows in situations where Touch ID cannot be used for user verification, and makes Chrome’s implementation align more closely with Safari’s.

2023-04-16 02:42 UTC, micolous approved these changes
Approving because of Chrome's bypass behaviour.

2023-04-16 02:48 UTC, merged