OpenSSL dependency update to support v3.x
kanidm/webauthn-rs pull request #340
Opened 2023-08-11 22:01 UTC by yaleman

Fixes #339

- [x] cargo test has been run and passes
- [ ] documentation has been updated with relevant examples (if relevant)

2023-08-13 22:44 UTC, Firstyear submitted a review, later dismissed
No issues from me, I'll let @micolous check too.

2023-08-16 22:46 UTC, Firstyear commented
```
libopenssl-devel-3.1.2-1.1.noarch
```
Seems to be working on my tumbleweed machine? Also confirmed it works on my mac with 3.1.2 as well. 

Do you potentially have a second openldap/libressl present?

2023-08-17 13:41 UTC, dmulder commented
> Do you potentially have a second openldap/libressl present?

Yes, I have libressl.

2023-08-17 23:21 UTC, Firstyear commented
Ahh that'll be it. libressl is broken wrt to openssl-rs normally, so it's likely a missing feature/flag/const in libressl.

2023-08-29 01:46 UTC, micolous requested changes

2023-08-29 01:46 UTC, micolous commented on Makefile
Please put this in a separate PR, it seems unrelated to this proposal.

2023-08-29 01:46 UTC, micolous commented on .github/dependabot.yml
> +---
Please put this in a separate PR after this one; we should get OpenSSL update out of the way first.

2023-08-29 01:46 UTC, micolous commented on Cargo.toml
> -exclude = [
Please split formatting changes into a separate PR before this one.

It makes it difficult to review your changes.

2023-08-29 01:46 UTC, micolous commented on fido-hid-rs/src/lib.rs
> -const U2FHID_TRANS_TIMEOUT: i32 = 3000;
This change is not related to the PR, please split this.

2023-08-29 03:51 UTC, yaleman commented
@micolous I've reverted what fmt changes I can and I don't have enough git-foo to convince the others to calm themselves, I hope that's OK.

2023-08-30 00:42 UTC, micolous approved these changes

2023-08-30 00:47 UTC, micolous commented
Thanks! CI failures on MSRV look like a separate issue not triggered by this change, I've opened https://github.com/kanidm/webauthn-rs/issues/346 about this.

2023-08-30 01:41 UTC, merged