Replace `println!` from library functions with configurable logging
kanidm/webauthn-rs pull request #424
Opened 2024-04-01 04:52 UTC by mishazharov

Developers building on this crate do not necessarily need logging to occur over `println!` when authenticating 2FA, so this commit replaces the print macros with logging macros

Fixes #

- [ ] cargo test has been run and passes
- [ ] documentation has been updated with relevant examples (if relevant)

2024-04-01 06:43 UTC, yaleman requested changes

2024-04-01 06:43 UTC, yaleman commented on webauthn-authenticator-rs/src/mozilla.rs
> +                        debug!(
this should be an error

2024-04-01 06:48 UTC, mishazharov commented on webauthn-authenticator-rs/src/mozilla.rs
> +                        debug!(
Thanks for taking a look, updated!

2024-04-03 05:28 UTC, mishazharov commented
It looks like there's some CI failures unrelated to this change:
```
error: package `bumpalo v3.15.4` cannot be built because it requires rustc 1.73.0 or newer, while the currently active rustc version is 1.70.0
Either upgrade to rustc 1.73.0 or newer, or use
cargo update -p bumpalo@3.15.4 --precise ver
where `ver` is the latest version of `bumpalo` supporting rustc 1.70.0
Error: Process completed with exit code 101.
```

2024-04-03 07:48 UTC, yaleman commented
@Firstyear how's this one look? Figured I'd ask because you've used it more

2024-04-03 07:49 UTC, yaleman submitted a review, later dismissed

2024-04-04 00:07 UTC, Firstyear reviewed
Actually @micolous would be the person to ask. There are some places where I think we use these messages as communication points for cli tools.

2024-04-04 00:07 UTC, Firstyear commented on webauthn-authenticator-rs/src/mozilla.rs
> +                    debug!("STATUS: Please select a device by touching one of them.");
I think this one needs to be info! at the least.

2024-04-08 05:43 UTC, micolous commented
> Actually @micolous would be the person to ask. There are some places where I think we use these messages as communication points for cli tools.

All the other backends use `info!`, `error!`, etc.; the Mozilla backend is the only one which *doesn't*.

The CLI tools I wrote touch the other backends (as they need to interact with it on a CTAP2 level, rather than an "Authenticator" level), so this would at least make things consistent (as they will eventually replace the Mozilla backend).

I believe the main user of the Mozilla backend is Kanidm's CLI tools – I don't know what makes sense there.

2024-04-08 22:33 UTC, yaleman commented
Libraries really should use the `log` primitives instead of `println` so the dependent apps can do what they need to from there...

2024-04-10 01:06 UTC, Firstyear approved these changes

2024-04-10 02:20 UTC, merged